name: build java project with maven 

on: 
    push:
      branches:
        - main
    workflow_dispatch:    
 ### the above trigger causes the workflow to be triggered when code is poushed to main. 

jobs:

    Build-test-deploy: ### this specifies the job name 
        runs-on: ubuntu-latest ### this specifies where the job should run
        steps:
            - name: clone repository
              uses: actions/checkout@v3  ### the first step clones our repo into the runner. 

            - name: install and setup java with maven 
              uses: actions/setup-java@v3
              with:
                distribution: 'adopt'
                java-version: '11' 
            - name: code build with maven 
              run:  mvn package   

   ### artifact upload --->>> when an artifact is created , and the job is done on the runner , AU helps upload that away from the runner into github.

            - name: upload maven artifact 
              uses: actions/upload-artifact@v3
              with:
                name: xashy-webapp
                path: target/*.war
            - name: Send Email on Success
              if: success()
              uses: dawidd6/action-send-mail@v3
              with:
                server_address: smtp.yourmailserver.com
                server_port: 465
                username: jayakuma998
                password: Ilovebebexashy123!@
                subject: GitHub Actions - Code Analysis Passed
            # List of recipients separated by comma
                to: akumajunior9@gmail.com
                from: YourName <noreply@example.com>
                body: The code analysis for ${{github.repository}} was successful!

            - name: Send Email on Failure
              if: failure()
              uses: dawidd6/action-send-mail@v3
              with:
                server_address: smtp.gmail.com
                server_port: 465
                username: jayakuma998
                password: Ilovebebexashy123!@
                subject: GitHub Actions - Code Analysis Failed
                to: akumajunior9@gmail.com
                from: YourName <noreply@example.com>
                body: The code analysis for ${{github.repository}} has failed. Check the logs for details.    
    
    Deploy-Artifact: 
        runs-on: ubuntu-latest
        needs: Build-test-deploy
        steps:         
         - name: clone repository
           id: clone
           uses: actions/checkout@v3  ### the first step clones our repo into the runner. 

         - name: install and setup java with maven 
           id: javainstall
           uses: actions/setup-java@v3
           with:
            distribution: 'adopt'
            java-version: '11'
         - name: Artifact download 
           uses: actions/download-artifact@v3
           with:
            name:  xashy-webapp
             
        
        

        ########## CONTEXT IN GITHUB ACTIONS #######  




    
    